// Generated by Wrangler by running `wrangler types --experimental-include-runtime --env-interface CloudflareEnv env.d.ts -c domains/agi-2025/wrangler.toml`

interface CloudflareEnv {
  kvcache: KVNamespace;
  BASE_URL: "agi-2025.com";
  TURNSTILE_SITE_KEY: "0x4AAAAAAAylKuDyLZriK5lA";
  ADMIN_PASSWORD: string;
  API_AUTH_TOKEN: string;
  TURNSTILE_SECRET_KEY: string;
  PUBLIC_TURNSTILE_SITE_KEY: string;
  ASSETS: Fetcher;
}
