// Generated by Wrangler by running `wrangler types --experimental-include-runtime --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  ADMIN_PASSWORD: string;
  API_AUTH_TOKEN: string;
  DOMAIN_OFFERS_DO: DurableObjectNamespace;
  ASSETS: Fetcher;
}
